### ISSUE TITLE
Noisy crackle with ARMSID still on latest firmware

### ISSUE THREAD

**Issue by oemsysadm** [twistedelectrons/TherapSID#36]
Running the TherapSID with an ARMSID or ARM2SID results in a lot of crackling or sizzling noise. I tried with the firmware marked "TSID_2.0_29_03_23" which was sent to me by you guys, and it has this problem.

Previously we went through some troubleshooting with the help of the good folks who make the ARMSID chips, and discovered that the TherapSID holds CS low for 4uS. Shortening it to 1uS makes the crackle go away, 2uS still keeps some crackle.

I'm curious to know which timings the firmware I just tried is using, and if there are plans to support the ARMSID range of SID replacement chips? Real SID chips are becoming rarer and rarer, and the ARMSID and ARM2SID is one of the best options out there for relatively authentic sound.

If using this timing does not create any other issue with the synth, I would like to suggest sticking to it?

I can provide sound samples from the same synth with both firmwares if you would like that, so you can hear the difference.

**Comment by Windfisch** [comment]
Hi oemsysadm, thanks for your detailed report!

I think this has already been fixed in the current version in the repo: [the relevant line is here](https://github.com/twistedelectrons/TherapSID/blob/main/src/sid.cpp#L219)

This was fixed only very recently, and ~1 month ago, the code looked like [this](https://github.com/twistedelectrons/TherapSID/blob/f3c148f6bd976feb84e50af9473ef9f0b0daae31/src/sid.cpp#L234) where it indeed was sleeping for 4 microseconds. I guess that's my fault and happened during The Great Refactor :D.

I'm pretty sure that Alex will release a new version pretty soon-ish (including this fix), because there's some more bugfixes under way.

If you're comfortable in building your own firmware, then latest `main` should already include the fix; `make firmware.syx` and you should be good. (At your own risk tho ;))

**Comment by twisted-electrons** [comment]
Hi Oemsysadm
PLease try the attached where all delays are removed from the send function.
I find it greatly improves the sound of my ARMSID pair.
I shall add an ARMSID mode to the web tool that disables the delays since the ARM likely requires delay.
[30 03 23.zip](https://github.com/twistedelectrons/TherapSID/files/11119891/30.03.23.zip)

**Comment by oemsysadm** [comment]
Hi, yes this greatly improved the quality of the sound! I was also sent a firmware via email that did not alleviate the problem. Is it feasible to do whatever it is you just did going forward? Maybe as a toggle-able option if it does impact other things in the synth when using a real SID or other replacement?

And if you plan to support the ARMSID family of chips, would it be possible to add chip specific configurations to the web tool, like setting emulation type (6581/8580), filter type, adsr bugfix on/off, etc?

P.S. I'm using an ARM2SID, not a pair of ARMSID chips, it's a slightly different product with a different firmware. Basically it emulates two chips (3 actually, with the third sending to both channels) in a single socket, with a second socket simply as extra pins to interface with.

**Comment by oemsysadm** [comment]
Actually, it seems the more voices you add (say 1, 2, or 3 sines), the more of that crackle is introduced. Adding a filter makes it more pronounced in these cases.

**Comment by oemsysadm** [comment]
So will these fixes be incorporated going forward, with testing on this particular SID replacement platform? If so we can probably close this issue.

**Comment by thomasj** [comment]
The ARMSID crackling was fixed with proper timing (and web setting removed) in #67, so suggesting this ticket to be closed as deprecated.
