### ISSUE TITLE
Random LFO shape needs some attention.

### ISSUE THREAD

**Issue by Sequence7** [twistedelectrons/TherapSID#78]
**Describe the bug**
the LFO on random just sounds kind of sickly and the rate knob seems like 75% of has little to no effect. Can be seen when linked to Tune or Fine, I know it's not using the sid chips random function but maybe that behavior would be good to model it on.  The sid itself reads it's own noise oscillator and sets a register to 0-255

**Steps To Reproduce**
Chain LFO to Tune or Fine, set lfo to LOOP, move RATE and DEPTH knobs

**Actual behavior**
It seems be very inconsistent to change values, perhaps it's overly often repeating the same value and rate has little effect compared to any other LFO shape. 

**Expected behavior**
More consistently random sounding and respond to RATE knob

**Additional context**
Perhaps some of the issue is the limited range and quantizing of tune, but even on FINE it doesn't seem right and rate knob doesn't seem to act as expected here.

**Comment by twisted-electrons** [comment]
@Sequence7 Thanks for raising this issue, likely an artifact of recently changing the LFO to bipolar in some cases. I'll check in with @thomasj before making changes as I'm afraid to interfer with the upcoming asid! Thanks

**Comment by twisted-electrons** [comment]
@Sequence7 Hi. I tweaked the noise LFO yesterday:
-the noise is generated consistently 4 times per LFO cycle (it was missfiring since the refactor)
-the LFO waveforms pulse to their beat

feel free to try it here:
https://github.com/twistedelectrons/TherapSID/blob/artifacts/pr79-firmware.syx?raw=true

You'll lose the asid player, let me know if you need the syx to get your tunes jaming!

**Comment by Sequence7** [comment]
@twisted-electrons thanks working as expected now, will close this if your happy with it. hopefully ASID in main build soon so I don't have to flip to test each.
